language: r
sudo: false
cache: packages

env:
  global:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)"
    - secure: hd5Zy/WZT5yazj8Xkad0fqhv5SeQUsZiPzAatXzU7riJnQ9cnHRMr111Qbhh9bHjCQwaPI4FBsxtIEQetYszUULpHhovXomDNcLbD+GAa1lng7XiSHt9SZkhRIXX746MFWle79ya/3/ne1g/ct6m9Z0DExRQAp7F2EsLjWY5Pt8=

repos:
  XRAN: https://xran.yihui.name

before_install:
  - "curl -L https://xran.yihui.name/.gitconfig -o ~/.gitconfig"

after_success:
  - "(curl -L https://xran.yihui.name/r-xran | bash)"
