language: c

sudo: false

env:
  matrix:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)"
  global:
    secure: hd5Zy/WZT5yazj8Xkad0fqhv5SeQUsZiPzAatXzU7riJnQ9cnHRMr111Qbhh9bHjCQwaPI4FBsxtIEQetYszUULpHhovXomDNcLbD+GAa1lng7XiSHt9SZkhRIXX746MFWle79ya/3/ne1g/ct6m9Z0DExRQAp7F2EsLjWY5Pt8=
addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base-dev
    - r-recommended

install:
  - "[ ! -d ~/bin ] && mkdir ~/bin || true"
  - "wget -q -O - https://github.com/yihui/crandalf/raw/master/inst/scripts/install-pandoc | bash"
  - "wget -q -O - http://yihui.name/xran/r-config | bash"
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"
  - Rscript -e "devtools::install_deps(dep = TRUE)"

cache:
  directories:
  - $HOME/R

script:
  - cd ..; rm -f *.tar.gz; R CMD build $R_PKG
  - R CMD check $R_PKG*.tar.gz --no-manual
  - cd $R_PKG

# deploy to XRAN
after_success:
  - export R_VIGNETTE=printr.html
  - "(wget -q -O - http://yihui.name/xran/r-xran | bash)"

